# Generated by Django 4.2.3 on 2023-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0003_model1_age_model1_date_created_model1_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="Default description"),
        ),
    ]
