# Generated by Django 4.2.3 on 2023-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0004_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(default="Default description", max_length=200),
        ),
    ]
