# Generated by Django 4.2.3 on 2023-07-20 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0005_alter_product_description"),
        ("magazine", "0006_auto_20230720_1400"),
    ]

    operations = []
